# RabbitMQ OAuth Example App
# Copyright 2020 VMware, Inc.
#
# This product is licensed to you under the Apache 2.0 license
# (the "License").  You may not use this product except in compliance
# with the Apache 2.0 License.
#
# This product may include a number of subcomponents with separate
# copyright notices and license terms. Your use of these subcomponents
# is subject to the terms and conditions of the subcomponent's license,
# as noted in the LICENSE file.

---
server:
  port: 8080

logging.level:
  org.springframework.security: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          sso:
            authorization-grant-type: client_credentials
            scope: uaa.resource,p-rabbitmq_SPACE-GUID.read:*/*,p-rabbitmq_SPACE-GUID.write:*/*,p-rabbitmq_SPACE-GUID.configure:*/*

# This disables automatic creation of spring.rabbitmq.* properties by the AmqpCfEnvProcessor for instance `rabbit` which are not needed to configure OAuth connection
cfenv:
  service:
    rabbit:
      enabled: false

example:
  rabbitmq:
    exchange:
      name: sample-exchange
    queue:
      name: sample-queue
    routingKey: sample-routing-key